modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/kawaiicakes/NoFortnite/issues"

[[mods]]
    modId="nomorefortnite"
    version="2.0.0"
    displayName="No More Fortnite!"
    displayURL="https://github.com/kawaiicakes/NoFortnite/"
    logoFile="nomorefortnite.png"
    credits="Thanks to ElocinDev for her simple config code. Also thanks to axolotlite for helping me test."
    authors="kawaiicakes"
    description='''
    Mod preventing players from building while in combat. Requires Modern Inhibited.
    '''

[[dependencies.nomorefortnite]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nomorefortnite]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.nomorefortnite]]
    modId="moderninhibited"
    mandatory=true
    versionRange="[1.0.1]"
    ordering="NONE"
    side="BOTH"
